server:
  port: 8888

db:
  host: 172.30.0.20
  port: 5000
  name: commerce_platform
  user: prod
  pwd: 123456

redis:
  host: 172.30.0.20
  port: 6379
  databaseNum: 2

cas:
  baseLmallDomain: http://lmall.lianjia.com:8070
  serverCasUrl: http://passport.lianjia.com:8088/cas
  clientCasUrl: http://lmall.lianjia.com:8070/cas
  filterLoginUrl: http://passport.lianjia.com:8088/cas/login?service=http://lmall.lianjia.com:8070/cas
  logoutUrl: http://passport.lianjia.com:8088/cas/logout
  indexUrl: http://lmall.fe.lianjia.com:3000/lmall/index.html

user:
  baseUrl: http://172.30.11.77:8080/uc

pay:
  lcoinWithholdPayUrl: http://172.30.0.20:8060/api/payment/lcoin/withhold
  withholdRefundUrl: http://172.30.0.20:8060/api/refund
  cashierPayUrl: http://pay.lmall.lianjia.com:8060/cashier/pay
  redirectUrl: http://lmall.fe.lianjia.com:3000/lmall/index.html#order
  callbackUrl: http://172.30.0.20:8070/api/order/pay/callback


